### PR TITLE
[INLONG-1069][Doc] Add Connector Binary file v1.18 to download page

### LINKED ISSUE #1069: [Improve][Doc] Connector Binary file v1.18 not listed in download page
### Description

Connector Binary file v1.18 is not listed in download page. However, they have been released on the maven repository of apache inlong.
https://repository.apache.org/content/groups/public/org/apache/inlong/inlong-distribution/2.0.0/inlong-distribution-2.0.0-sort-connectors-flink-v1.18.tar.gz

image

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by PeterZh6**
Fixes #1069 

### Motivation
Connector Binary file v1.18 is not listed in download page. However, they have been released on the maven repository of apache inlong. It should be added to reflect this change, while also resolving confusions as some examples in the website require users to use connector-v1.18

### Modifications
Added one more row for Connector Binary file v1.18

### Verifying this change

image

- [x] Make sure that the change passes the CI checks.

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:

- [ ] This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by dockerzhang** [comment]
@PeterZh6 1.13 is not recommended now, you can remove it, only keep 1.15 and 1.18.

**Review by aloyszhang — APPROVED** [review]
LGTM

**Review by aloyszhang — CHANGES_REQUESTED** [review]
Why are there so many changes in `package-lock.json`？

**Comment by PeterZh6** [comment]
> Why are there so many changes in `package-lock.json`？

Sorry for this. Problem fixed.

**Review by aloyszhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Pull request merged**
