### PR TITLE
[INLONG-576] Optimize document style layout

### PR DESCRIPTION
**Pull request by bluewang**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes https://github.com/apache/inlong-website/issues/576

### CODE REVIEW

**Comment by dockerzhang** [comment]
what is the effect of this PR change?

**Comment by bluewang** [comment]
> what is the effect of this PR change?

docs

It looks better than before

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Review by leezng — COMMENTED** [review]
It doesn't seem to fit well on a small screen.

**Comment by dockerzhang** [comment]
> It doesn't seem to fit well on a small screen.

@bluewang PTAL, thanks.

**Comment by leezng** [comment]
After discussion, we do not recommend changing the underlying design of the framework, which is more customized, and it may be troublesome for us to upgrade its framework version in the future.

So, close the PR first.

**Pull request closed without merging**
