### PR TITLE
[INLONG-789][SDK] Fix the explanation of the meaning of the HTTP return value is not synchronized with the sample code

### LINKED ISSUE #789: [Bug][SDK] The explanation of the meaning of the HTTP return value is not synchronized with the sample code
### What happened

image
image

### What you expected to happen

The explanation of the meaning of the HTTP return value is synchronized with the sample code.

### How to reproduce

See website:
https://inlong.apache.org/docs/sdk/dataproxy-sdk/http/

### Environment

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xuesongxs**
- Fixes #789

### CODE REVIEW

**Review by justinwwhuang — COMMENTED** [review]
the value of success is 1
image

**Comment by xuesongxs** [comment]
> the value of success is 1 image

This return value has been confirmed with the dataproxy developer and has been modified in the sample code. This is a previously omitted change, please check issue 777.

**Comment by justinwwhuang** [comment]
> the value of success is 1 image

sorry, the directory is dataproxy-sdk，misunderstood it as the dataproxy sdk return code.

**Review by justinwwhuang — APPROVED** [review]
LGTM

**Review by dockerzhang — APPROVED** [review]

**Pull request merged**
